#
# A template for creating TOML configuration files for the YellowDog Python
# script examples. TOML key names are case-sensitive.
#
# Note that this is only a subset of the available properties. Please consult
# The README file for a complete list.
#

[common]  ######################################################################

    # YellowDog Application key and secret
    # Required
    # --------------------------------------------------------------------------
    key = "<INSERT-KEY-HERE>"
    secret = "<INSERT-SECRET-HERE>"

    # A namespace for grouping YellowDog objects, e.g., the name of an
    # overall project for which YellowDog is being used
    # Required
    # --------------------------------------------------------------------------
    namespace = "my_namespace"

    # A name tag to subdivide objects within the namespace, e.g., to
    # tag a given set of tasks, nodes and data objects
    # Required
    # --------------------------------------------------------------------------
    tag = "my_tag"

[workRequirement]  ############################################################

    # Arguments and environment to pass to the Task.
    # Optional
    # --------------------------------------------------------------------------
    # arguments = [] # List of strings
    # environment = {}  # Dictionary, e.g.: {A = "ONE", B = "TWO"}

    # Worker tags: list of tags (strings) to match the tags associated
    # with Workers
    # A list of strings
    # Optional
    # --------------------------------------------------------------------------
    # workerTags = []

    # The number of times a Task is retried if it fails
    # Optional
    # --------------------------------------------------------------------------
    # maximumTaskRetries = 0

    # Number of times to submit the task
    # Optional
    # --------------------------------------------------------------------------
    # taskCount = 1

    # The name of a JSON file containing the description of a Work
    # Requirement
    # Optional
    # --------------------------------------------------------------------------
    # workRequirementData = "my_tasks.json"

[workerPool]  #################################################################

    # The Compute Requirement Template to use
    # Required
    # --------------------------------------------------------------------------
    templateId = ""

    # The initial number of nodes to provision in the Worker Pool
    # Optional
    # --------------------------------------------------------------------------
    # targetInstanceCount = 1

    # The minimum number of nodes down to which the Worker Pool can be
    # auto-scaled
    # Optional
    # --------------------------------------------------------------------------
    # minNodes = 0

    # The maximum number of nodes up to which the Worker Pool can be
    # auto-scaled
    # Optional: Is set to the greater of targetInstanceCount and 1 by default
    # maxNodes = 1

    # The number of Workers to create on each node
    # Optional
    # --------------------------------------------------------------------------
    # workersPerNode = 1

    # The Worker Tag to associate with the Worker(s)
    # Optional
    # --------------------------------------------------------------------------
    # workerTag = "My_Worker_Tag"

    # name of a JSON file containing the full description of a Worker Pool
    # The specification will overwrite all values in this file except for
    # the namespace and tag.
    # Optional
    # --------------------------------------------------------------------------
    # workerPoolData = "my_worker_pool.json"
