"""
Strings used for keys in the JSON input file.
"""

ARGS = "args"
AUTO_FAIL = "auto_fail"
BASH_SCRIPT = "bash_script"
COMPLETED_TASK_TTL = "completed_task_ttl"
DEPENDENT_ON = "dependent_on"
ENV = "env"
EXCLUSIVE_WORKERS = "exclusive_workers"
EXECUTABLE = "executable"
FULFIL_ON_SUBMIT = "fulfil_on_submit"
INPUT_FILES = "input_files"
INSTANCE_TYPES = "instance_types"
MAX_RETRIES = "max_retries"
MAX_WORKERS = "max_workers"
MIN_WORKERS = "min_workers"
NAME = "name"
OUTPUT_FILES = "output_files"
PRIORITY = "priority"
PROVIDERS = "providers"
RAM = "ram"
REGIONS = "regions"
TASKS = "tasks"
TASKS_PER_WORKER = "tasks_per_worker"
TASK_GROUPS = "task_groups"
TASK_TYPE = "task_type"
TASK_TYPES = "task_types"
VCPUS = "vcpus"
WORKER_TAGS = "worker_tags"
