"""
Strings used for keys in the JSON input file.
"""

ARGS = "args"
AUTO_FAIL = "auto_fail"
BASH_SCRIPT = "bash_script"
DEPENDS_ON = "depends_on"
ENV = "env"
EXCLUSIVE_WORKERS = "exclusive_workers"
EXECUTABLE = "executable"
INPUT_FILES = "input_files"
MAX_RETRIES = "max_retries"
NAME = "name"
OUTPUT_FILES = "output_files"
TASKS = "tasks"
TASK_GROUPS = "task_groups"
TASK_TYPE = "task_type"
TASK_TYPES = "task_types"
WORKER_TAGS = "worker_tags"
