"""
Strings used for keys in the JSON input file.
"""

ARGS = "args"
BASH_SCRIPT = "bash_script"
DEPENDS_ON = "depends_on"
ENV = "env"
INPUT_FILES = "input_files"
MAX_RETRIES = "max_retries"
NAME = "name"
OUTPUT_FILES = "output_files"
TASKS = "tasks"
TASK_GROUPS = "task_groups"
WORKER_TAGS = "worker_tags"
